baseURL = "https://www.katherineduffieldhill.com"
languageCode = "en-us"
title = "Katherine Hill MSHP"
sectionPagesMenu = "sections"
themesDir = "themes"
theme = "blank"

# [[menu.sections]]
#   identifier = "resume"
#   name = "Resum√©"
#   weight = 10
#   url = "TODO_Dropbox_URL"
